### ISSUE TITLE
你好，想和你请教一下

### ISSUE THREAD

**Issue by BetaLi** [yanthink/blog#1]
你好，为什么打包后访问就会出现404错误呢？我现在也在基于AntdPro开发各网站，但是打包后会出现这样的错误，你的项目写的很好，我再dev环境跑起来没有问题，但是打包后用http-server跑起来就会出现404错误，希望能够指教一下。

**Comment by yanthink** [comment]
这个项目默认使用 `BrowserHistory` 模式，需要server端支持。
如果你想启用 `HashHistory` 模式，可以修改 `src/index.js` 的配置。
```javascript
import createHistory from 'history/createHashHistory';
```
[关于 `BrowserHistory` 和 `HashHistory` 的区别](https://blog.csdn.net/qq_29854831/article/details/79636095) 

顺便放一个 `BrowserHistory` 模式下 `nginx` 的配置
```
location / {
    try_files $uri $uri/ /index.html?$query_string;
}
```

**Comment by BetaLi** [comment]
后台我是用Node写的，只能属于入门级，在写API接口的时候有什么比较好的建议吗？
